#!/bin/bash
apt-get install -y xfce4 tightvncserver wget && apt-get update
apt-get install xfce4 -y
echo "xfce4-session" > ~/.xsession
apt install firefox -y
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ./google-chrome-stable_current_amd64.deb
sudo su
cd $HOME
mkdir .vnc
touch .vnc/xstartup
echo "#!/bin/sh
startxfce4 &" > ~/.vnc/xstartup
apt-get update && apt upgrade -yy
